### PR TITLE
[Major] Adds Bootloader and CI/CD Release and Test Integrations

### LINKED ISSUE #3: Assembly bootloader to rust

### LINKED ISSUE #10: Unit Test & Integration Test

### LINKED ISSUE #11: Automatic Release Action on merged Pull Request

### LINKED ISSUE #12: Test Action

### PR DESCRIPTION
**Pull request by Mrgoblings**
### Referenced issue
Resolves #3
Resolves #10
Resolves #11
Resolves #12 

### Description
Adds bootloader that loads from Assembly to the Rust '_start' function.
Adds Actions for automating Releasing and Testing 

- Includes a Makefile to compile, link, produce .iso image and run with qemu. 

To run use:
```sh
make
```

To compile without run use:
```sh
make no-run
```

### Breaking change?
Is the change you are introducing going to affect already other existing resources? 

- [ ] No, this code change does not affect other project resources.
- [x] Yes, the code changes modify already existing project resources.

### CODE REVIEW

**Review by angel-penchev — DISMISSED** [review]
LGTM, I just have some minor comments about the inclusion of some files and stylistic changes.

**Review by angel-penchev — APPROVED** [review]
LGTM 👍

**Review by angel-penchev — APPROVED** [review]

**Review by angel-penchev — APPROVED** [review]
LGTM

**Review by angel-penchev — APPROVED** [review]

**Comment by apenchev-rms** [comment]
This issue looks like it also resolves #12. Can you please confirm and add it as "Resolved" to the PR description as well, if that is the case?

**Comment by angel-penchev** [comment]
This issue looks like it also resolves #12. Can you please confirm and add it as "Resolved" to the PR description as well, if that is the case?

**Pull request merged**
